name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_path: build/linux/x64/release/bundle
            asset_name: qubase_mcp-linux-x64.tar.gz
            build_target: linux
            apk_build: true
          - os: windows-latest
            output_path: build/windows/x64/Runner/Release
            asset_name: qubase_mcp-windows-x64.zip
            build_target: windows
            apk_build: false
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        if: matrix.apk_build
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Android SDK
        if: matrix.apk_build
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0'
      
      - name: Create empty .env file
        run: touch .env

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build ${{ matrix.build_target }}
        shell: bash
        run: |
          flutter build ${{ matrix.build_target }} --release
          if [ "${{ matrix.apk_build }}" == "true" ]; then
            flutter build apk --release
          fi
      
      - name: Package Linux App
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build/linux/x64/release/bundle
          tar -czf "${GITHUB_WORKSPACE}/${{ matrix.asset_name }}" *
      
      - name: Package macOS App
        if: matrix.os == 'macos-latest'
        run: |
          brew install create-dmg
          create-dmg \
            --volname "qubase_mcp" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "qubase_mcp.app" 200 190 \
            --hide-extension "qubase_mcp.app" \
            --app-drop-link 600 185 \
            "${{ matrix.asset_name }}" \
            "${{ matrix.output_path }}"
      
      - name: Package Windows App
        if: matrix.os == 'windows-latest'
        run: |
          Copy-Item -Path "windows/sqlite3.dll" -Destination "${{ matrix.output_path }}" -Force
          Compress-Archive -Path "${{ matrix.output_path }}/*" -DestinationPath "${{ matrix.asset_name }}" -Force

      - name: Package Android APK
        if: matrix.apk_build
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk qubase_mcp-android.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.apk_build && 'qubase_mcp-android' || matrix.build_target }}
          path: |
            ${{ matrix.asset_name }}
            ${{ matrix.apk_build && 'qubase_mcp-android.apk' || '' }}
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.asset_name }}
            ${{ matrix.apk_build && 'qubase_mcp-android.apk' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

